version: '3'

services:
  kea-dhcp-cmap-guest:
    # build: .
    image: widecamp1903/kea-dhcp
    container_name: kea-dhcp-camp-guest
    restart: unless-stopped
    volumes:
      - ./kea/200_camp-guest.conf:/etc/kea/kea-dhcp4.conf:ro
    ports:
      - 203.178.156.1:67:67
    network_mode: host

